title:             SoftWyze
email:             softwyzeinvestments@gmail.com
description:       The science of software
author:            Christian Majuta
baseurl:           "/"
url:               "http://softwyze.github.io"

# Social Profiles
twitter_username:  softwyze
github_username:   softwyze
facebook_username: softwyze

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
